### PR TITLE
Adding custom attribute range for NEL NLD0670 and Oclaro TRB100.

### PR DESCRIPTION
**Pull request by samisaab**
PR for Issue #44

### CODE REVIEW

**Comment by scott-emery** [comment]
Looks good. In the future you should work on a different branch than "master".

Acked-By: Scott Emery <scotte@cumulusnetworks.com>

**Comment by ishidawataru** [comment]
@samisaab We also need to add these custom ranges in the hostif and module attributes.

**Comment by samisaab** [comment]
Commit amended.

**Comment by ishidawataru** [comment]
thanks

**Pull request merged**
