### PR TITLE
Support API mode

### PR DESCRIPTION
**Pull request by TetsuyaMurakami**
The shared library which can be used by other programs in order to configure the optical module is supported based on the taish infrastructure.

### CODE REVIEW

**Comment by ishidawataru** [comment]
Why don't other programs just directly links `libtai.so` ?

**Comment by TetsuyaMurakami** [comment]
We assume normally one application is taking care of the configuration for the optical module. In our case, our switch program process is managing the switch chipset as well as the optical module. If using the taish at the same time for the debugging, exclusion control might be needed because multiple applications are using libtai.so. Hence, the application managing the optical module is using taish library instead. Normally, it is ok for this application to use the TAI API directly instead. But if using taish library, this application can provide the debug shell and also it does not require the complicate exclusion control because the single application can manage the optical module and provide the debug shell.

**Comment by ishidawataru** [comment]
@iTetsuyaMurakami I see your point.

> Hence, the application managing the optical module is using taish library instead

How is your application getting module_id of the modules which is created in [create_module()](https://github.com/Telecominfraproject/oopt-tai/blob/cf533144e0d94f1536efaaf306d328872d07ec11/tools/taish/tai_shell.cpp#L177) ?

Are you accessing the global variable [modules](https://github.com/Telecominfraproject/oopt-tai/blob/cf533144e0d94f1536efaaf306d328872d07ec11/tools/taish/tai_shell.cpp#L168)?

I think it would be better to let the application to create modules, netifs, hostifs.

**Comment by ishidawataru** [comment]
We could implement a `libtai.so` which links to an actual vendor `libtai.so`, provides debug features, and will be linked by the host application.

**Comment by TetsuyaMurakami** [comment]
@ishidawataru Yes. Our application can get the module id via TAI. In fact, we are also using libtai.so in our application. However, we would like to support command line CLI like BCM Shell in our application for debugging purpose. For this, our application leverages taish infrastructure.

**Comment by ishidawataru** [comment]
I understand your use case and agree on having such library/software in either this repo or `oopt-tai-implementation` repo.

I'm thinking what is the best way to implement this.

I assume that your application is delegating the creation of `module`, `netif` and `hostif` to taish library and the application is accessing the global variable `modules` to get module IDs when it needs to do set/get attributes.

Instead of that, I think it is better to let the application create all TAI objects and has the responsibility of managing them.
It would be nice if taish library can be implemented as another libtai.so (let's name it libtai-sh.so for now) which links to libtai.so provided by vendors.

In this case, libtai-sh.so works as kind of proxy + debug shell server.

**Comment by ishidawataru** [comment]
@iTetsuyaMurakami Can we discuss this PR next week at the TAI workshop? I think it is better to make this as a TAI library which exposes `tai.h` interface as I mentioned earlier.

**Comment by TetsuyaMurakami** [comment]
Sure. We will discuss next week. I will reach to London on this coming Monday.

**Comment by ishidawataru** [comment]
Opened https://github.com/Telecominfraproject/oopt-tai/pull/52 to support API use case.

**Comment by ishidawataru** [comment]
Closing this. Now `taish` functionality (API) can be embedded in the TAI adapter host by using `libtaigrpc.so`

**Pull request closed without merging**
